// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CustomCommands     string
	TicketConfigs      string
	TicketParticipants string
	Tickets            string
}{
	CustomCommands:     "custom_commands",
	TicketConfigs:      "ticket_configs",
	TicketParticipants: "ticket_participants",
	Tickets:            "tickets",
}
